import { NextResponse } from "next/server";
import { z } from "zod";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { firstValidationMessage } from "@/lib/validation";
const Action=z.discriminatedUnion("action",[
 z.object({action:z.literal("rename"),title:z.string().trim().min(2).max(120)}),
 z.object({action:z.literal("add"),canonicalSlug:z.string().regex(/^passage-\d+[a-z]?$/)}),
 z.object({action:z.literal("update_item"),itemId:z.string().uuid(),notes:z.string().max(20000),tags:z.array(z.string().trim().min(1).max(40)).max(20)}),
 z.object({action:z.literal("remove_item"),itemId:z.string().uuid()}),
 z.object({action:z.literal("move_item"),itemId:z.string().uuid(),direction:z.enum(["up","down"])})
]);
async function context(slug:string){const db=await createSupabaseServerClient();if(!db)return{error:NextResponse.json({error:"Supabase is not configured."},{status:503})};const{data:{user}}=await db.auth.getUser();if(!user)return{error:NextResponse.json({error:"Sign in to manage guides."},{status:401})};const{data:guide}=await db.from("user_study_guides").select("id,title,slug,created_at,updated_at").eq("owner_id",user.id).eq("slug",slug).maybeSingle();if(!guide)return{error:NextResponse.json({error:"Guide not found."},{status:404})};return{db,user,guide}}
export async function GET(_request:Request,{params}:{params:Promise<{slug:string}>}){const{slug}=await params;const c=await context(slug);if("error" in c)return c.error;const{data:items,error}=await c.db.from("user_study_items").select("id,canonical_passage_id,notes,personal_tags,sort_order,canonical_passages(slug,internal_reference)").eq("guide_id",c.guide.id).order("sort_order");if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({guide:c.guide,items:items??[]})}
export async function PATCH(request:Request,{params}:{params:Promise<{slug:string}>}){try{const{slug}=await params,input=Action.parse(await request.json());const c=await context(slug);if("error" in c)return c.error;if(input.action==="rename"){const{error}=await c.db.from("user_study_guides").update({title:input.title}).eq("id",c.guide.id);if(error)return NextResponse.json({error:error.message},{status:400})}
 if(input.action==="add"){const{data:passage}=await c.db.from("canonical_passages").select("id").eq("slug",input.canonicalSlug).single();if(!passage)return NextResponse.json({error:"Passage not found."},{status:404});const{data:existing}=await c.db.from("user_study_items").select("id").eq("guide_id",c.guide.id).eq("canonical_passage_id",passage.id).maybeSingle();if(existing)return NextResponse.json({error:"That passage is already in this guide."},{status:400});const{data:last}=await c.db.from("user_study_items").select("sort_order").eq("guide_id",c.guide.id).order("sort_order",{ascending:false}).limit(1).maybeSingle();const{error}=await c.db.from("user_study_items").insert({guide_id:c.guide.id,canonical_passage_id:passage.id,notes:"",personal_tags:[],sort_order:(last?.sort_order??-1)+1});if(error)return NextResponse.json({error:error.message},{status:400})}
 if(input.action==="update_item"){const{error}=await c.db.from("user_study_items").update({notes:input.notes.trim(),personal_tags:input.tags}).eq("id",input.itemId).eq("guide_id",c.guide.id);if(error)return NextResponse.json({error:error.message},{status:400})}
 if(input.action==="remove_item"){const{error}=await c.db.from("user_study_items").delete().eq("id",input.itemId).eq("guide_id",c.guide.id);if(error)return NextResponse.json({error:error.message},{status:400})}
 if(input.action==="move_item"){const{data:items}=await c.db.from("user_study_items").select("id,sort_order").eq("guide_id",c.guide.id).order("sort_order");const index=(items??[]).findIndex(x=>x.id===input.itemId),target=input.direction==="up"?index-1:index+1;if(index>=0&&target>=0&&target<(items??[]).length){const current=items![index],other=items![target];await c.db.from("user_study_items").update({sort_order:-1}).eq("id",current.id);await c.db.from("user_study_items").update({sort_order:current.sort_order}).eq("id",other.id);const{error}=await c.db.from("user_study_items").update({sort_order:other.sort_order}).eq("id",current.id);if(error)return NextResponse.json({error:error.message},{status:400})}}
 return NextResponse.json({ok:true})}catch(error){const validationMessage=firstValidationMessage(error,"Invalid guide update.");if(validationMessage)return NextResponse.json({error:validationMessage},{status:400});return NextResponse.json({error:"The guide could not be updated."},{status:500})}}
export async function DELETE(_request:Request,{params}:{params:Promise<{slug:string}>}){const{slug}=await params;const c=await context(slug);if("error" in c)return c.error;const{error}=await c.db.from("user_study_guides").delete().eq("id",c.guide.id);if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({deleted:true})}
