import { readdir,readFile } from "node:fs/promises";
import path from "node:path";
import { createClient } from "@supabase/supabase-js";
import { checksum,normalizeSearchText,validateSourceFile } from "./source-utils.mjs";
const url=process.env.SUPABASE_URL||process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;
if(!url||!key){console.error("Set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY. The service role must never be exposed to browser code.");process.exit(1)}
const supabase=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const dir=path.resolve("data/sources");const files=(await readdir(dir)).filter(x=>x.endsWith(".json")).sort();
async function upsertOne(filename,file){const report=validateSourceFile(file,{filename});if(!report.valid)throw new Error(`${filename} failed validation.`);const digest=checksum(file);const{data:existing}=await supabase.from("import_jobs").select("id,status").eq("filename",filename).eq("checksum",digest).maybeSingle();if(existing?.status==="completed"){console.log(`SKIP ${filename}: matching completed import.`);return}
 const{data:job,error:jobError}=await supabase.from("import_jobs").upsert({filename,checksum:digest,status:"running",validation_report:report},{onConflict:"filename,checksum"}).select("id").single();if(jobError)throw jobError;
 try{let{data:work,error}=await supabase.from("works").upsert({slug:"havamal",title:"Hávamál",original_language:"Old Norse",description:"The Hávamál within the Poetic Edda.",status:"published"},{onConflict:"slug"}).select("id").single();if(error)throw error;
  const e=file.edition;let{data:license,error:licenseError}=await supabase.from("license_records").upsert({name:e.licenseName,status:e.licenseStatus,attribution_required:Boolean(e.attributionText),public_display_allowed:e.fullTextDisplayAllowed,noncommercial_reuse_allowed:e.noncommercialReuseAllowed,commercial_reuse_allowed:e.commercialReuseAllowed,excerpts_allowed:true,full_text_display_allowed:e.fullTextDisplayAllowed,adaptations_allowed:false,quote_card_export_allowed:e.quoteCardExportAllowed,downloadable_export_allowed:e.downloadableExportAllowed,reference_url:file.passages[0]?.license_reference,jurisdiction_notes:e.publicDomainJurisdictionNotes,verified_at:e.dateLastVerified,verified_by:e.verifiedBy},{onConflict:"name"}).select("id").single();if(licenseError)throw licenseError;
  let{data:source,error:sourceError}=await supabase.from("source_records").upsert({work_id:work.id,title:e.editionTitle,provider:e.sourceProvider,source_location:e.sourceLocation,creator:e.translator||e.editor,publication_year:e.publicationYear,original_publisher:e.originalPublisher,language:e.language,license_id:license.id,attribution_text:e.attributionText,source_notes:e.sourceNotes,enabled:e.enabled,date_last_verified:e.dateLastVerified,verified_by:e.verifiedBy},{onConflict:"work_id,source_location"}).select("id").single();if(sourceError)throw sourceError;
  let{data:edition,error:editionError}=await supabase.from("editions").upsert({work_id:work.id,source_record_id:source.id,slug:e.slug,edition_title:e.editionTitle,translator:e.translator,editor:e.editor,publication_year:e.publicationYear,language:e.language,status:e.enabled?"published":"draft"},{onConflict:"slug"}).select("id").single();if(editionError)throw editionError;
  for(const [index,p] of file.passages.entries()){const order=Number.parseInt(p.source_stanza_number,10)||index+1;let{data:canonical,error:canonicalError}=await supabase.from("canonical_passages").upsert({work_id:work.id,slug:p.canonical_slug,internal_reference:`Aligned passage ${p.source_stanza_number}`,printed_order:order,section_label:p.section,status:p.review_status==="published"?"published":"draft"},{onConflict:"slug"}).select("id").single();if(canonicalError)throw canonicalError;
   let{data:ep,error:epError}=await supabase.from("edition_passages").upsert({edition_id:edition.id,source_stanza_number:p.source_stanza_number,section_heading:p.section,printed_order:order,text_lines:p.text_lines,old_norse_lines:p.old_norse_lines||[],normalized_search_text:normalizeSearchText([p.source_stanza_number,e.translator,e.editionTitle,p.section,...p.themes,...p.text_lines,...(p.old_norse_lines||[])].join(" ")),prose_note:p.prose_note,footnotes:p.footnotes,source_page:p.source_page,source_reference:p.source_reference,license_reference:p.license_reference,review_status:p.review_status,published_at:p.review_status==="published"?new Date().toISOString():null},{onConflict:"edition_id,source_stanza_number"}).select("id").single();if(epError)throw epError;
   const confidenceMap={exact:1,high:.9,medium:.7,uncertain:.35};const canonicalTargets=p.canonical_span?.length?p.canonical_span:[p.canonical_slug];for(const targetSlug of canonicalTargets){let target=canonical;if(targetSlug!==p.canonical_slug){const{data:extra,error:extraError}=await supabase.from("canonical_passages").upsert({work_id:work.id,slug:targetSlug,internal_reference:targetSlug.replace("passage-","Aligned passage "),printed_order:Number.parseInt(targetSlug.replace(/\D/g,""),10)||order,section_label:p.section,status:p.review_status==="published"?"published":"draft"},{onConflict:"slug"}).select("id").single();if(extraError)throw extraError;target=extra}const{error:alignmentError}=await supabase.from("passage_alignments").upsert({canonical_passage_id:target.id,edition_passage_id:ep.id,confidence:confidenceMap[p.alignment_confidence]??.35,editorial_notes:p.alignment_note||null,spans_multiple_canonical:canonicalTargets.length>1||p.alignment_relation==="one_to_many",multiple_source_to_one:p.alignment_relation==="many_to_one"},{onConflict:"canonical_passage_id,edition_passage_id"});if(alignmentError)throw alignmentError;}
   const{data:stanzaCategory,error:categoryError}=await supabase.from("forum_categories").select("id").eq("slug","stanza-discussion").maybeSingle();if(categoryError)throw categoryError;if(stanzaCategory){const{error:threadError}=await supabase.from("forum_threads").upsert({slug:`discussion-${p.canonical_slug}`,category_id:stanzaCategory.id,canonical_passage_id:canonical.id,canonical_slug:p.canonical_slug,title:`Reader discussion: ${p.canonical_slug}`,status:"open",is_locked:false},{onConflict:"canonical_passage_id"});if(threadError)throw threadError}
   for(const themeSlug of p.themes){const{data:theme,error:themeError}=await supabase.from("themes").select("id").eq("slug",themeSlug).maybeSingle();if(themeError)throw themeError;if(theme){const{error:ptError}=await supabase.from("passage_themes").upsert({canonical_passage_id:canonical.id,theme_id:theme.id},{onConflict:"canonical_passage_id,theme_id"});if(ptError)throw ptError}}
  }
  await supabase.from("import_jobs").update({status:"completed",completed_at:new Date().toISOString()}).eq("id",job.id);console.log(`IMPORTED ${filename}: ${file.passages.length} passages.`)
 }catch(error){await supabase.from("import_jobs").update({status:"failed",completed_at:new Date().toISOString()}).eq("id",job.id);await supabase.from("import_errors").insert({import_job_id:job.id,severity:"error",message:error.message});throw error}}
for(const filename of files){const file=JSON.parse(await readFile(path.join(dir,filename),"utf8"));await upsertOne(filename,file)}
